CREATE TABLE usuarios (
    usuarios_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    usuario VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(255),
    nivel_de_acesso INT,
    nome_fantasia VARCHAR(255),
    cpf VARCHAR(14),
    cnpj VARCHAR(18),
    data_nascimento DATE,
    fone VARCHAR(15),
    celular VARCHAR(15),
    cep VARCHAR(10),
    numero VARCHAR(5),
    rua VARCHAR(255),
    estado VARCHAR(255),
    cidade VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    ie VARCHAR(20),
    rg VARCHAR(20),
    qtd_acessos INT,
    ultimo_acesso DATETIME,
    receber_email INTEGER DEFAULT(0)
);
